services:
  selenium-tool:
    build:
      context: .
      dockerfile: Dockerfile
    image: linzaixian/selenium-tool:latest
    container_name: selenium-tool
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      SE_VNC_PASSWORD: selenium
    volumes:
      - ./custom.yml:/app/config/custom.yml:ro
    ports:
      - "7900:7900"