spring:
  application:
    name: selenium-tool
  main:
    banner-mode: "off"
  config:
    import:
      - "classpath:custom.yml"
      - "optional:file:/app/config/custom.yml"

automation:
  run-on-startup: true
  schedule:
    zone: "Asia/Shanghai"
  browser:
    headless: true
    no-sandbox: true
    disable-dev-shm-usage: true
    page-stay-seconds: 3
    page-load-timeout: 2m
  cookie-cloud:
    cache-file: "/app/data/cookiecloud-cache.json"
